apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/enesdemir143/apex
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: apex-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
  - target:
      kind: Deployment
      name: apex-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  - target:
      kind: ConfigMap
      name: apex-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: production
