apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apex
  namespace: apex
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  rules:
    - host: apex.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apex-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apex-frontend
                port:
                  name: http
