apiVersion: v1
kind: Service
metadata:
  name: apex-frontend
  namespace: apex
  labels:
    app.kubernetes.io/name: apex-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apex-frontend
  ports:
    - name: http
      port: 8501
      targetPort: http
